server:
  port: 8080

spring:
  application:
    name: gallery-api

  profiles:
    active: ${GALLERY_ENVIRONMENT:local}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  management:
    endpoints:
      web:
        exposure:
          include: health, info, metrics, prometheus
    endpoint:
      health:
        show-details: always

  springdoc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://localhost:6666/gallery_db
    username: warus
    password: pass
    driver-class-name: org.postgresql.Driver

logging:
  level:
    root: INFO
    org.springframework: WARN
    org.hibernate.SQL: DEBUG
    com.example.gallery: DEBUG
  #  file:
  #    name: logs/gallery.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

upload:
  path: /Users/marek.wargocki@schibsted.com/Downloads/uploaded

jwt:
  secret: supersecretkey12345678901234567890123456789012
  expiration: 86400000 # 1 miliseconds (1000 * 60 * 60 * 24)

---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

logging:
  level:
    root: INFO
    org.springframework: WARN
    org.hibernate.SQL: DEBUG
    com.example.gallery: DEBUG
  #  file:
  #    name: logs/gallery.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

upload:
  path: ./

jwt:
  secret: supersecretkey12345678901234567890123456789012
  expiration: 86400000 # 1 miliseconds (1000 * 60 * 60 * 24)
